// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExchangeRatingModel
    {
        /// <summary>
        /// Initializes a new instance of the ExchangeRatingModel class.
        /// </summary>
        public ExchangeRatingModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExchangeRatingModel class.
        /// </summary>
        public ExchangeRatingModel(double rating, string exchangeName = default(string))
        {
            ExchangeName = exchangeName;
            Rating = rating;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeName")]
        public string ExchangeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rating")]
        public double Rating { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
