// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ExecutionStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExecutionStatus
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Fill")]
        Fill,
        [EnumMember(Value = "PartialFill")]
        PartialFill,
        [EnumMember(Value = "Cancelled")]
        Cancelled,
        [EnumMember(Value = "Rejected")]
        Rejected,
        [EnumMember(Value = "New")]
        New,
        [EnumMember(Value = "Pending")]
        Pending
    }
    internal static class ExecutionStatusEnumExtension
    {
        internal static string ToSerializedValue(this ExecutionStatus? value)
        {
            return value == null ? null : ((ExecutionStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ExecutionStatus value)
        {
            switch( value )
            {
                case ExecutionStatus.Unknown:
                    return "Unknown";
                case ExecutionStatus.Fill:
                    return "Fill";
                case ExecutionStatus.PartialFill:
                    return "PartialFill";
                case ExecutionStatus.Cancelled:
                    return "Cancelled";
                case ExecutionStatus.Rejected:
                    return "Rejected";
                case ExecutionStatus.New:
                    return "New";
                case ExecutionStatus.Pending:
                    return "Pending";
            }
            return null;
        }

        internal static ExecutionStatus? ParseExecutionStatus(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return ExecutionStatus.Unknown;
                case "Fill":
                    return ExecutionStatus.Fill;
                case "PartialFill":
                    return ExecutionStatus.PartialFill;
                case "Cancelled":
                    return ExecutionStatus.Cancelled;
                case "Rejected":
                    return ExecutionStatus.Rejected;
                case "New":
                    return ExecutionStatus.New;
                case "Pending":
                    return ExecutionStatus.Pending;
            }
            return null;
        }
    }
}
