// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Instrument
    {
        /// <summary>
        /// Initializes a new instance of the Instrument class.
        /// </summary>
        public Instrument()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Instrument class.
        /// </summary>
        public Instrument(string name = default(string), string exchange = default(string), string baseProperty = default(string), string quote = default(string))
        {
            Name = name;
            Exchange = exchange;
            BaseProperty = baseProperty;
            Quote = quote;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchange")]
        public string Exchange { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "base")]
        public string BaseProperty { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quote")]
        public string Quote { get; private set; }

    }
}
