// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderType
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Market")]
        Market,
        [EnumMember(Value = "Limit")]
        Limit
    }
    internal static class OrderTypeEnumExtension
    {
        internal static string ToSerializedValue(this OrderType? value)
        {
            return value == null ? null : ((OrderType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderType value)
        {
            switch( value )
            {
                case OrderType.Unknown:
                    return "Unknown";
                case OrderType.Market:
                    return "Market";
                case OrderType.Limit:
                    return "Limit";
            }
            return null;
        }

        internal static OrderType? ParseOrderType(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return OrderType.Unknown;
                case "Market":
                    return OrderType.Market;
                case "Limit":
                    return OrderType.Limit;
            }
            return null;
        }
    }
}
