// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderExecutionStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderExecutionStatus
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Fill")]
        Fill,
        [EnumMember(Value = "PartialFill")]
        PartialFill,
        [EnumMember(Value = "Cancelled")]
        Cancelled,
        [EnumMember(Value = "Rejected")]
        Rejected,
        [EnumMember(Value = "New")]
        New,
        [EnumMember(Value = "Pending")]
        Pending
    }
    internal static class OrderExecutionStatusEnumExtension
    {
        internal static string ToSerializedValue(this OrderExecutionStatus? value)
        {
            return value == null ? null : ((OrderExecutionStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderExecutionStatus value)
        {
            switch( value )
            {
                case OrderExecutionStatus.Unknown:
                    return "Unknown";
                case OrderExecutionStatus.Fill:
                    return "Fill";
                case OrderExecutionStatus.PartialFill:
                    return "PartialFill";
                case OrderExecutionStatus.Cancelled:
                    return "Cancelled";
                case OrderExecutionStatus.Rejected:
                    return "Rejected";
                case OrderExecutionStatus.New:
                    return "New";
                case OrderExecutionStatus.Pending:
                    return "Pending";
            }
            return null;
        }

        internal static OrderExecutionStatus? ParseOrderExecutionStatus(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return OrderExecutionStatus.Unknown;
                case "Fill":
                    return OrderExecutionStatus.Fill;
                case "PartialFill":
                    return OrderExecutionStatus.PartialFill;
                case "Cancelled":
                    return OrderExecutionStatus.Cancelled;
                case "Rejected":
                    return OrderExecutionStatus.Rejected;
                case "New":
                    return OrderExecutionStatus.New;
                case "Pending":
                    return OrderExecutionStatus.Pending;
            }
            return null;
        }
    }
}
