// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PositionModel
    {
        /// <summary>
        /// Initializes a new instance of the PositionModel class.
        /// </summary>
        public PositionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PositionModel class.
        /// </summary>
        public PositionModel(double positionVolume, double maintMarginUsed, double realisedPnL, double unrealisedPnL, double initialMarginRequirement, double maintenanceMarginRequirement, string symbol = default(string), double? value = default(double?), double? availableMargin = default(double?))
        {
            Symbol = symbol;
            PositionVolume = positionVolume;
            MaintMarginUsed = maintMarginUsed;
            RealisedPnL = realisedPnL;
            UnrealisedPnL = unrealisedPnL;
            Value = value;
            AvailableMargin = availableMargin;
            InitialMarginRequirement = initialMarginRequirement;
            MaintenanceMarginRequirement = maintenanceMarginRequirement;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionVolume")]
        public double PositionVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maintMarginUsed")]
        public double MaintMarginUsed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "realisedPnL")]
        public double RealisedPnL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unrealisedPnL")]
        public double UnrealisedPnL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "availableMargin")]
        public double? AvailableMargin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "initialMarginRequirement")]
        public double InitialMarginRequirement { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maintenanceMarginRequirement")]
        public double MaintenanceMarginRequirement { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
