// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResponseMessage
    {
        /// <summary>
        /// Initializes a new instance of the ResponseMessage class.
        /// </summary>
        public ResponseMessage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResponseMessage class.
        /// </summary>
        public ResponseMessage(string message = default(string), object model = default(object))
        {
            Message = message;
            Model = model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public object Model { get; set; }

    }
}
