// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TradingBot.Exchanges.Concrete.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Best Bid/Offer Snapshots &amp; Historical Bins
    /// </summary>
    public partial class Quote
    {
        /// <summary>
        /// Initializes a new instance of the Quote class.
        /// </summary>
        public Quote()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Quote class.
        /// </summary>
        public Quote(System.DateTime timestamp, string symbol, double? bidSize = default(double?), double? bidPrice = default(double?), double? askPrice = default(double?), double? askSize = default(double?))
        {
            Timestamp = timestamp;
            Symbol = symbol;
            BidSize = bidSize;
            BidPrice = bidPrice;
            AskPrice = askPrice;
            AskSize = askSize;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bidSize")]
        public double? BidSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bidPrice")]
        public double? BidPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "askPrice")]
        public double? AskPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "askSize")]
        public double? AskSize { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Symbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Symbol");
            }
        }
    }
}
