// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace Lykke.ExternalExchangesApi.Exchanges.BitMex.AutorestClient.Models
{
    public partial class ConnectedUsers
    {
        /// <summary>
        /// Initializes a new instance of the ConnectedUsers class.
        /// </summary>
        public ConnectedUsers()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectedUsers class.
        /// </summary>
        public ConnectedUsers(double? users = default(double?), double? bots = default(double?))
        {
            Users = users;
            Bots = bots;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "users")]
        public double? Users { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bots")]
        public double? Bots { get; set; }

    }
}
