// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Microsoft.Rest;
using Newtonsoft.Json;

namespace Lykke.ExternalExchangesApi.Exchanges.BitMex.AutorestClient.Models
{
    /// <summary>
    /// Swap Funding History
    /// </summary>
    public partial class Funding
    {
        /// <summary>
        /// Initializes a new instance of the Funding class.
        /// </summary>
        public Funding()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Funding class.
        /// </summary>
        public Funding(System.DateTime timestamp, string symbol, System.DateTime? fundingInterval = default(System.DateTime?), double? fundingRate = default(double?), double? fundingRateDaily = default(double?))
        {
            Timestamp = timestamp;
            Symbol = symbol;
            FundingInterval = fundingInterval;
            FundingRate = fundingRate;
            FundingRateDaily = fundingRateDaily;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fundingInterval")]
        public System.DateTime? FundingInterval { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fundingRate")]
        public double? FundingRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fundingRateDaily")]
        public double? FundingRateDaily { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Symbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Symbol");
            }
        }
    }
}
