// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Collections.Generic;
using Microsoft.Rest;
using Newtonsoft.Json;

namespace Lykke.ExternalExchangesApi.Exchanges.BitMex.AutorestClient.Models
{
    public partial class InstrumentInterval
    {
        /// <summary>
        /// Initializes a new instance of the InstrumentInterval class.
        /// </summary>
        public InstrumentInterval()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InstrumentInterval class.
        /// </summary>
        public InstrumentInterval(IList<string> intervals, IList<string> symbols)
        {
            Intervals = intervals;
            Symbols = symbols;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intervals")]
        public IList<string> Intervals { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbols")]
        public IList<string> Symbols { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Intervals == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Intervals");
            }
            if (Symbols == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Symbols");
            }
        }
    }
}
