// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Microsoft.Rest;
using Newtonsoft.Json;

namespace Lykke.ExternalExchangesApi.Exchanges.BitMex.AutorestClient.Models
{
    /// <summary>
    /// Level 2 Book Data
    /// </summary>
    public partial class OrderBook
    {
        /// <summary>
        /// Initializes a new instance of the OrderBook class.
        /// </summary>
        public OrderBook()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderBook class.
        /// </summary>
        public OrderBook(string symbol, double level, double? bidSize = default(double?), double? bidPrice = default(double?), double? askPrice = default(double?), double? askSize = default(double?), System.DateTime? timestamp = default(System.DateTime?))
        {
            Symbol = symbol;
            Level = level;
            BidSize = bidSize;
            BidPrice = bidPrice;
            AskPrice = askPrice;
            AskSize = askSize;
            Timestamp = timestamp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "level")]
        public double Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bidSize")]
        public double? BidSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bidPrice")]
        public double? BidPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "askPrice")]
        public double? AskPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "askSize")]
        public double? AskSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime? Timestamp { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Symbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Symbol");
            }
        }
    }
}
