// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Microsoft.Rest;
using Newtonsoft.Json;

namespace Lykke.ExternalExchangesApi.Exchanges.BitMex.AutorestClient.Models
{
    /// <summary>
    /// Exchange Statistics
    /// </summary>
    public partial class Stats
    {
        /// <summary>
        /// Initializes a new instance of the Stats class.
        /// </summary>
        public Stats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Stats class.
        /// </summary>
        public Stats(string rootSymbol, string currency = default(string), double? volume24h = default(double?), double? turnover24h = default(double?), double? openInterest = default(double?), double? openValue = default(double?))
        {
            RootSymbol = rootSymbol;
            Currency = currency;
            Volume24h = volume24h;
            Turnover24h = turnover24h;
            OpenInterest = openInterest;
            OpenValue = openValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rootSymbol")]
        public string RootSymbol { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "volume24h")]
        public double? Volume24h { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "turnover24h")]
        public double? Turnover24h { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "openInterest")]
        public double? OpenInterest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "openValue")]
        public double? OpenValue { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RootSymbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RootSymbol");
            }
        }
    }
}
