// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TimeInForce.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TimeInForce
    {
        [EnumMember(Value = "GoodTillCancel")]
        GoodTillCancel,
        [EnumMember(Value = "FillOrKill")]
        FillOrKill
    }
    internal static class TimeInForceEnumExtension
    {
        internal static string ToSerializedValue(this TimeInForce? value)
        {
            return value == null ? null : ((TimeInForce)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this TimeInForce value)
        {
            switch( value )
            {
                case TimeInForce.GoodTillCancel:
                    return "GoodTillCancel";
                case TimeInForce.FillOrKill:
                    return "FillOrKill";
            }
            return null;
        }

        internal static TimeInForce? ParseTimeInForce(this string value)
        {
            switch( value )
            {
                case "GoodTillCancel":
                    return TimeInForce.GoodTillCancel;
                case "FillOrKill":
                    return TimeInForce.FillOrKill;
            }
            return null;
        }
    }
}
