// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ExchangeConnector.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TradeBalanceModel
    {
        /// <summary>
        /// Initializes a new instance of the TradeBalanceModel class.
        /// </summary>
        public TradeBalanceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TradeBalanceModel class.
        /// </summary>
        public TradeBalanceModel(double totalbalance, double unrealisedPnL, double maringAvailable, double marginUsed, string accountCurrency = default(string))
        {
            AccountCurrency = accountCurrency;
            Totalbalance = totalbalance;
            UnrealisedPnL = unrealisedPnL;
            MaringAvailable = maringAvailable;
            MarginUsed = marginUsed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountCurrency")]
        public string AccountCurrency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalbalance")]
        public double Totalbalance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unrealisedPnL")]
        public double UnrealisedPnL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maringAvailable")]
        public double MaringAvailable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marginUsed")]
        public double MarginUsed { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
