version: '2'

services:
  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  # TradingBot
  tradingbot:
    build:
      context: TradingBot/
      dockerfile: Dockerfile
    hostname: tradingbot
    #ports:
    # - "5000:5000"
    depends_on:
      - rabbit
    volumes:
      - ~/Projects/Lykke/FxData:/var/FxData

  # AlphaEngineJava
  alphaenginejava:
    build:
      context: ../../RelatedProjects/alpha-engine/
      dockerfile: Dockerfile
    hostname: alphaenginejava
    depends_on:
      - rabbit
