// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TradingBot.Exchanges.Concrete.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserCommission
    {
        /// <summary>
        /// Initializes a new instance of the UserCommission class.
        /// </summary>
        public UserCommission()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserCommission class.
        /// </summary>
        public UserCommission(double? makerFee = default(double?), double? takerFee = default(double?), double? settlementFee = default(double?), double? maxFee = default(double?))
        {
            MakerFee = makerFee;
            TakerFee = takerFee;
            SettlementFee = settlementFee;
            MaxFee = maxFee;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "makerFee")]
        public double? MakerFee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "takerFee")]
        public double? TakerFee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settlementFee")]
        public double? SettlementFee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxFee")]
        public double? MaxFee { get; set; }

    }
}
